### PR TITLE
Add support for seamless re-execs without lost requests or requests sent to old processes

### PR DESCRIPTION
**Pull request by Rudd-O**
... parent stops listening and lingers for ten seconds handling slow requests before giving up, while the child picks up the listening socket immediately and continues serving requests.

### CODE REVIEW

**Comment by ManuelAmadorAditazz** [comment]
I would refine the code as per " you should probably not use "noCloseOnExec" and instead use cmd.ExtraFiles
 it is what it was made for
<Rudd-XXX> oh!
 wat, there is a thing for this?" but I have no idea atm how to do this.  I'd welcome pointers.

**Comment by rcrowley** [comment]
@Rudd-O I unfortunately can't merge this.  I would like to support UNIX domain sockets but can't do so exclusively.  And as stated in #6, I'm also not interested in hard-coding the exit strategy to "just give it time."

**Comment by ManuelAmadorAditazz** [comment]
I will check in your patch to make the system work with all types of
sockets.

Give me options for the exit strategy, cos I did not understand that part
very well.

**Comment by rcrowley** [comment]
@ManuelAmadorAditazz just off the top of my head one might want to delay for some fixed period of time longer than requests are supposed to take, wait until all active connections have closed, or wait until all active connections have finished the current request.  The point is only that it isn't up to `goagain` how your requirements are enforced.

**Comment by ManuelAmadorAditazz** [comment]
That's a sensible observation.  In any case I will probably keep my code
around for a while until such time that I need this flexibility.  The
differences between our trees are minimal in any case, and I can keep
merging.

**Pull request closed without merging**
