### PR TITLE
Removes log calls

### PR DESCRIPTION
**Pull request by daaku**
This removes the log calls from the library.

### CODE REVIEW

**Comment by rcrowley** [comment]
What's your motivation for removing the logging?  I tend to prefer information like this than be forced to gather it indirectly.

**Comment by daaku** [comment]
I guess I prefer libraries not to log stuff, or if they do, provide the ability to turn it off.

**Comment by rcrowley** [comment]
A fair point.  I'll think about it.  Thanks for the patch.

**Comment by rcrowley** [comment]
I've used this now for several production services and have always wanted the logging.

**Pull request closed without merging**
